#
# PROGRAM:     Assign1
# PROGRAMMER:  Branden Hidalgo
# ZID:         Z1663752
#

# Compiler variables
CCFLAGS = -Wall

# Rule to link object code files to create executable file
Assign1: Assign1.cc
	g++ $(CCFLAGS) Assign1.cc -o Assign1

clean:
	rm Assign1
