#
# PROGRAM:    ASSIGNMENT 2
# PROGRAMMER: BRANDEN HIDALGO
# ZID:        Z1663752

# Compiler Variables
CCFLAGS = -Wall

# Rule to link object code files to create executable file
Assign2: Assign2.cc
	g++ $(CCFLAGS) Assign2.cc -o Assign2

clean:
	rm Assign2
